( cd /usr/lib64; rm -rf libgnat-11.so )
( cd /usr/lib64; rm -rf libgnat.so )
( cd /usr/lib64; rm -rf libgnarl-11.so )
( cd /usr/lib64; rm -rf libgnarl.so )
( cd /usr/lib64; rm -rf libgnat.a )
( cd /usr/lib64; rm -rf libgnarl.a )
( cd /usr/lib64; rm -rf libgmem.a )
