( cd /usr/%lib%; rm -rf libgnat-6.so )
( cd /usr/%lib%; ln -sf %GCC_GNATLIB_PATH%/libgnat-6.so )
( cd /usr/%lib%; rm -rf libgnat.so )
( cd /usr/%lib%; ln -fs libgnat-6.so libgnat.so )
( cd /usr/%lib%; rm -rf libgnarl-6.so )
( cd /usr/%lib%; ln -fs %GCC_GNATLIB_PATH%/libgnarl-6.so )
( cd /usr/%lib%; rm -rf libgnarl.so )
( cd /usr/%lib%; ln -fs libgnarl-6.so libgnarl.so )
( cd /usr/%lib%; rm -rf libgnat.a )
( cd /usr/%lib%; ln -fs %GCC_GNATLIB_PATH%/libgnat.a )
( cd /usr/%lib%; rm -rf libgnarl.a )
( cd /usr/%lib%; ln -sf %GCC_GNATLIB_PATH%/libgnarl.a )
( cd /usr/%lib%; rm -rf libgmem.a )
( cd /usr/%lib%; ln -sf %GCC_GNATLIB_PATH%/libgmem.a )
