( cd /usr/%lib%; rm -rf libgnat-%ma_ver%.so )
( cd /usr/%lib%; ln -sf %GCC_GNATLIB_PATH%/libgnat-%ma_ver%.so )
( cd /usr/%lib%; rm -rf libgnat.so )
( cd /usr/%lib%; ln -fs libgnat-%ma_ver%.so libgnat.so )
( cd /usr/%lib%; rm -rf libgnat-%ma_ver%.%mi_ver%.so )
( cd /usr/%lib%; ln -sf libgnat-%ma_ver%.so libgnat-%ma_ver%.%mi_ver%.so )
( cd /usr/%lib%; rm -rf libgnarl-%ma_ver%.so )
( cd /usr/%lib%; ln -fs %GCC_GNATLIB_PATH%/libgnarl-%ma_ver%.so )
( cd /usr/%lib%; rm -rf libgnarl.so )
( cd /usr/%lib%; ln -fs libgnarl-%ma_ver%.so libgnarl.so )
( cd /usr/%lib%; rm -rf libgnarl-%ma_ver%.%mi_ver%.so )
( cd /usr/%lib%; ln -fs libgnarl-%ma_ver%.so libgnarl-%ma_ver%.%mi_ver%.so)
( cd /usr/%lib%; rm -rf libgnat.a )
( cd /usr/%lib%; ln -fs %GCC_GNATLIB_PATH%/libgnat.a )
( cd /usr/%lib%; rm -rf libgnarl.a )
( cd /usr/%lib%; ln -sf %GCC_GNATLIB_PATH%/libgnarl.a )
( cd /usr/%lib%; rm -rf libgmem.a )
( cd /usr/%lib%; ln -sf %GCC_GNATLIB_PATH%/libgmem.a )
